<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Stardust</RootNamespace>
    <TargetFramework>net9.0</TargetFramework>
    <Title>the Desktop manager of the future</Title>
    <RepositoryUrl>git.finite.ovh/Stardust</RepositoryUrl>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <NeutralLanguage>en-AU</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Setup\" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Anotar.Serilog.Fody" Version="6.0.0" />
		<PackageReference Include="DiscUtils" Version="0.16.13" />
		<PackageReference Include="Mono.Cecil" Version="0.11.6" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Stardust.Core\Stardust.Core.vbproj" />
	  <ProjectReference Include="..\Stardust.Display\Stardust.Display.vbproj" />
	  <ProjectReference Include="..\Stardust.FileSystem.BaseFS\Stardust.FileSystem.BaseFS.vbproj" />
	  <ProjectReference Include="..\Stardust.Hdd\Stardust.Hdd.csproj" />
	  <ProjectReference Include="..\Stardust.JavaUi\Stardust.JavaUi.vbproj" />
	  <ProjectReference Include="..\Apps\Shell\Shell.csproj" />
	</ItemGroup>
</Project>
